services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    annotations:
    - de.lr-projects.description=File sharing and collaboration
    - de.lr-projects.sso=true
    volumes:
    - ./nextcloud_data:/var/www/html
    networks:
    - frontend
    - backend-nextcloud
    labels:
    - traefik.enable=true
    - traefik.http.routers.nextcloud.rule=Host(`nextcloud.medion.lr-projects.de`)
    - traefik.http.routers.nextcloud.entrypoints=websecure
    - traefik.http.routers.nextcloud.tls=true
    - traefik.http.routers.nextcloud.tls.certresolver=cloudflare
    - traefik.http.routers.nextcloud.middlewares=nextcloud-middlewares-secure-headers
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.accessControlMaxAge=100
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.sslRedirect=true
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.stsSeconds=63072000
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.stsIncludeSubdomains=true
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.stsPreload=true
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.forceSTSHeader=true
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.customFrameOptionsValue=SAMEORIGIN
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.contentTypeNosniff=true
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.browserXssFilter=true
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.referrerPolicy=no-referrer
    - "traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.featurePolicy=camera'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow
    - traefik.http.middlewares.nextcloud-middlewares-secure-headers.headers.customResponseHeaders.server=
    - traefik.http.routers.nextcloud.middlewares=nextcloud-caldav
    - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
    - traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
    - traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/
    - traefik.docker.network=frontend
    - com.centurylinklabs.watchtower.enable=true
    env_file: .env
    environment:
    - MYSQL_HOST=database
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    - REDIS_HOST=redis
    depends_on:
    - database
    - redis
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2.5G

  database:
    image: mariadb:11.8
    restart: always
    env_file: .env
    networks:
    - backend-nextcloud
    environment:
    - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD}
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    volumes:
    - database:/var/lib/mysql
    labels:
    - com.centurylinklabs.watchtower.enable=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    env_file: .env
    networks:
      - backend-nextcloud
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    annotations:
    - de.lr-projects.description=Nextcloud Redis Cache
    - de.lr-projects.sso=false
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  office:
    container_name: office
    image: collabora/code:latest
    restart: always
    networks:
      - frontend
    labels:
    - traefik.enable=true
    - traefik.http.routers.office.rule=Host(`office.medion.lr-projects.de`)
    - traefik.http.routers.office.entrypoints=websecure
    - traefik.http.routers.office.tls=true
    - traefik.http.routers.office.tls.certresolver=cloudflare
    - traefik.docker.network=frontend
    - com.centurylinklabs.watchtower.enable=true
    annotations:
    - de.lr-projects.description=LibreOffice Online
    - de.lr-projects.sso=false
    environment:
    - aliasgroup1=https://nextcloud.lr-projects.de
    - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    cap_add:
      - MKNOD
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
volumes:
  database: null
networks:
  frontend:
    external: true
  backend-nextcloud: null
