services:
  nextcloud:
    image: nextcloud:latest
    restart: always
    annotations:
    - de.lr-projects.description=File sharing and collaboration
    - de.lr-projects.sso=true
    volumes:
    - ./nextcloud_data:/var/www/html
    networks:
    - frontend
    - backend-nextcloud
    labels:
    - traefik.enable=true
    - traefik.http.routers.nextcloud.rule=Host(`nextcloud.medion.lr-projects.de`)
    - traefik.http.routers.nextcloud.entrypoints=websecure
    - traefik.http.routers.nextcloud.tls=true
    - traefik.http.routers.nextcloud.tls.certresolver=cloudflare
    - com.centurylinklabs.watchtower.enable=true
    env_file: .env
    environment:
    - MYSQL_HOST=database
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    - REDIS_HOST=redis
    depends_on:
    - database
    - redis
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2.5G

  database:
    image: mariadb:12.2
    restart: always
    env_file: .env
    networks:
    - backend-nextcloud
    environment:
    - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD}
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    volumes:
    - database:/var/lib/mysql
    labels:
    - com.centurylinklabs.watchtower.enable=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    env_file: .env
    networks:
      - backend-nextcloud
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    annotations:
    - de.lr-projects.description=Nextcloud Redis Cache
    - de.lr-projects.sso=false
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  office:
    container_name: office
    image: collabora/code:latest
    restart: always
    networks:
      - frontend
    labels:
    - traefik.enable=true
    - traefik.http.routers.office.rule=Host(`office.lr-projects.de`) || Host(`office.medion.lr-projects.de`)
    - traefik.http.routers.office.entrypoints=websecure
    - traefik.http.routers.office.tls=true
    - traefik.http.routers.office.tls.certresolver=cloudflare
    - traefik.docker.network=frontend
    - com.centurylinklabs.watchtower.enable=true
    annotations:
    - de.lr-projects.description=LibreOffice Online
    - de.lr-projects.sso=false
    environment:
    - aliasgroup1=https://nextcloud.lr-projects.de
    - domain=nextcloud\\.lr-projects\\.de
    - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    cap_add:
      - MKNOD
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
volumes:
  database:
networks:
  frontend:
    external: true
  backend-nextcloud:
